image: ruby:2.5.1
services:
  - postgres:9.5
variables:
  POSTGRES_DB: jobvacancy_test
  POSTGRES_USER: jobvacancy
  POSTGRES_PASSWORD: jobvacancy
  DB_HOST: postgres
stages:
  - build
  - deploy_staging
  - deploy_production

job_build:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
    - ruby -v
    - which ruby
    - gem install bundler --no-ri --no-rdoc
    - bundle install --without staging production
    - RACK_ENV=test bundle exec rake

job_deploy_staging:
  stage: deploy_staging
  script:
  - gem install dpl -v 1.10.12
  - dpl --provider=heroku --app=$HEROKU_STAGING_APP --api-key=$HEROKU_API_KEY
  only:
    variables:
      - $STAGING_BRANCH == $CI_COMMIT_REF_NAME

job_deploy_production:
  stage: deploy_production
  script:
  - gem install dpl -v 1.10.12
  - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP --api-key=$HEROKU_API_KEY
  only:
    variables:
      - $PRODUCTION_BRANCH == $CI_COMMIT_REF_NAME